# Generated by Django 4.0.2 on 2022-02-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
        ('jwt_auth', '0005_remove_user_city_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ManyToManyField(related_name='jwt_auth', to='city.City'),
        ),
    ]
